### ISSUE TITLE
Dangling reference

### ISSUE THREAD

**Issue by martingasser** [Cycling74/min-api#131]
This returns a dangling reference and causes a crash:

https://github.com/Cycling74/min-api/blob/ffc55da72cc5cf2c31893cb8b12ffea1d65b364e/include/c74_min_symbol.h#L117

Why not simply like this?

```
operator std::string() const {
  return s->s_name;
}
```

**Comment by martingasser** [comment]
> This returns a dangling reference and causes a crash:
> 
> https://github.com/Cycling74/min-api/blob/ffc55da72cc5cf2c31893cb8b12ffea1d65b364e/include/c74_min_symbol.h#L117
> 
> Why not simply like this?
> 
> ```
> operator std::string() const {
>   return s->s_name;
> }
> ```

Update: It crashes when compiled with the current version of clang (Apple LLVM version 10.0.1 (clang-1001.0.46.4) in my case). The binary included with the Package Manager release of min-devkit seems to work. After recompiling, it crashes again.

In any case, returning (lvalue or rvalue) references to local temporaries amounts to undefined behavior.

**Comment by tap** [comment]
Thanks for the report. You are absolutely correct and we should be returning a copy.
