### ISSUE TITLE
Error in documentation "GuideToWritingMinObjects.md"

### ISSUE THREAD

**Issue by sncheca** [Cycling74/min-api#149]
Hi all,

First of all, thanks for making this awesome api! It is very fun and intuitive to use and well documented. 

In the "Configuring Inlets and Outlets at Runtime" section of "[GuideToWritingMinObjects.md](https://github.com/Cycling74/min-api/blob/master/doc/GuideToWritingObjects.md)", I think there is an incorrect use of the `unique_pointer` type. Here's the code snippet:

```
private:
    std::vector< std::unique_ptr<inlet<>> >	m_inlets;
    std::vector< std::unique_ptr<outlet<>> >	m_outlets;

clone(const atoms& args = {}) {
	if (args.empty())
		error("argument required");
  
  	auto inlet_count = args[0];
  	auto outlet_count = inlet_count * 2;
  
	for (auto i=0; i < inlet_count; ++i) {
      		auto an_inlet = std::make_unique<inlet<>>(this, "(bang) my assist message");
		m_inlets.push_back( an_inlet );
	}

  	for (auto i=0; i < outlet_count; ++i) {
      		auto an_outlet = std::make_unique<outlet<>>(this, "my outlet assist message");
		m_outlets.push_back( an_outlet );
	}
}
```

You cannot `push_back()` a unique pointer, since you cannot make copies of a unique pointer, by definition. I fixed this by either
1. Changing the `m_input` vector and `m_output` vector to `shared_ptr`s and then changing `make_unique` to `make_shared` (or you can do the same with `weak_ptr`s)
2. Changing the line of the `push_back` to this: `m_outlets.push_back( std::move(an_outlet) );` which moves the unique pointer instead of copying it.  

I'm not really sure which is a better solution, and I'd imagine it depends on your use case. 
I'd appreciate if the documentation could be updated! Thanks!

**Comment by tap** [comment]
You are absolutely correct! Thanks for the note!
