### ISSUE TITLE
dozens of bugs exposed by warnings; min-api needs overhaul to address

### ISSUE THREAD

**Issue by diablodale** [Cycling74/min-api#154]
Hi. I'm finding so many bugs through compiler warnings that it doesn't make sense to continue listing them one-by-one. Cycling74 can see and fix them in bulk by turning on level 4x warnings. I've filed multiple other issues and additional example of the many dozens is below.

## Setup

* VS Community 2019 v16.6.0
* max api commit 1c06b88fc30da0931b6dfa4a874bc081afe00926
* min api commit 210d5da
* min.jit.stencil.cpp from the min-devkit

## Repro

1. Remove any 'ignore warning' flags from your cmake harness
2. Add `/W4` to your cmake add_compile_options()
3. Compile min.jit.stencil.cpp

## Result

Dozens of bugs and warnings. You'll have to go one by one to see which is a legitimate bug.  I've logged some of them in separate issues. And I'll give one additional example here

```
C:\repos-nobackup\min-api\include\c74_min_string.h(47): warning C4100: 'glue': unreferenced formal parameter
```

That is a legitimate bug. The function's code is errant to always put a space between joined strings rather than using the `glue` parameter.

```c++
inline string join(const vector<string>& input, char glue = ' ') {
        string output;

        for (const auto& str : input) {
            output += str;
            output += " ";    // <------------- BUG
        }
        trim(output);
        return output;
    }
```

**Comment by tap** [comment]
Thanks for the detailed report. Please feel free to submit a Pull Request and we can review and try to work it in.

**Comment by diablodale** [comment]
Hahaha, to continue the joke, please send me a email so I can give you my invoicing information. The week or two of work needed to fix the readily found min-api problems are more than I can do without a formal agreement setup.
;-)
The economics don't work without compensation. You're welcome to email anytime. I can fit in the work while I'm working on another project.

I'll use the legacy 6.x SDK until min-api is brought up to production quality. We all have priorities.
Cheers :-)

**Comment by tap** [comment]
Enjoy!

**Comment by robtherich** [comment]
string join bug is fixed. closing out.
