### ISSUE TITLE
annoying endl;

### ISSUE THREAD

**Issue by omarcostahamido** [Cycling74/min-api#170]
I'm including a header.h that is using namespace std.
whenever I do something like cout<<(...)<<endl; it always complains that `Reference to 'endl' is ambiguous`.
Anyone experiencing this?

**Comment by robtherich** [comment]
users are not recommended to define a top level `using namespace std; `

**Comment by omarcostahamido** [comment]
wait, but what if I have to use it for my header file (not the main cpp file for the object)?
