### ISSUE TITLE
threading help, plz!

### ISSUE THREAD

**Issue by omarcostahamido** [Cycling74/min-api#171]
I'm trying to run this function that opens another program and returns its output.
Naturally, it takes time. I can't seem to be able to make it work on its own and not get either the max UI (main thread) or the timing objects like metro (scheduler) all bogged down.
Can anyone help?
```
void exec(const char* cmd) {
		std::array<char, 128> buffer;
		std::string result;
		std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd, "r"), pclose);
		if (!pipe) {
			std::cerr<<"failed to execute code"<<std::endl;
			throw std::runtime_error("popen() failed!");
		}
		while (fgets(buffer.data(), buffer.size(), pipe.get()) != nullptr) {
			result += buffer.data();
		}
		cout<<result<<endl;
//		output.send(result);
		return;
	}
```
(adapted from [here](https://stackoverflow.com/questions/478898/how-do-i-execute-a-command-and-get-the-output-of-the-command-within-c-using-po))

**Comment by robtherich** [comment]
I believe this is the same question asked in both mindevkit and on the forums. closing out a duplicate.
