### ISSUE TITLE
std library <algorithm> needs to be included in C74_min_api.h 

### ISSUE THREAD

**Issue by scblakely** [Cycling74/min-api#201]
I have just set up a new computer with VC++ and pulled _min-devkit_ from github.

Compilation of the examples failed - a prominent failure was missing **std::clamp**.

Adding 

`#include <algorithm>`

to **C74_min_api.h** resolved the issue so that all the examples compiled.

**Comment by isabelgk** [comment]
This was fixed with a [recent commit](https://github.com/Cycling74/min-api/commit/663c117c4b1df804e7b254ba9d655b71bfb63e77), but min-devkit needed an update of its submodules. It should be fixed now.
